### ISSUE TITLE
where i can get the align.data file

### ISSUE THREAD

**Issue by mapleyuan** [danielroich/PTI#13]
hi guys, 
i run the align_data.py and i can't found the file below:
dlib = './pretrained_models/align.dat'

**Comment by danielroich** [comment]
Hi @mapleyuan 

This happened because too many people have downloaded the same file from Google Drive and it entered a protective mode which **did not download the files when asked**. This is why you don't see the file even when running the download command.


I have upgraded the notebook,  it is now working with PyDrive making the download phase work all the time.

Please try again and let me know if it works now.
Daniel
