### ISSUE TITLE
use_locality_regularization = False?

### ISSUE THREAD

**Issue by lastapple** [danielroich/PTI#31]
In your code "./configs/hyperparameters.py", the "use_locality_regularization" is False? The space_regulizer_loss is not calculated ?

**Comment by danielroich** [comment]
For this specific configuration, space_regulizer_loss  is not calculated.
You can activate it by changing the value to True.
If you plan to re-use the generator then I recommend changing the value, it will keep the W space intact.

The value is False by default because it enables faster inversion for experiments and one time usages

**Comment by lastapple** [comment]
Thank you for your quick reply！As the loss is your contribution, I used to wonder why this parameter was set to false

**Comment by rmokady** [comment]
> lastapple

This is also useful when multiple images inverted simultaneously, but most users, especially non-expert, usually invert one image at a time.
