### ISSUE TITLE
SG and SG2 issue

### ISSUE THREAD

**Issue by FeiiYin** [danielroich/PTI#44]
Hi, thanks for the impressive work, which has raised a great impact.
In the original paper, I wondered about the difference between SG, SG w+ and the first step of PTI.
Both SG, PTI optimize the original W space, while SG w+ employ the w+ space.
SG and SG w+ take more steps to optimize. And all the 3 methods employ noise regularization.
Is there any other difference that I missed?

**Comment by danielroich** [comment]
No, it sounds just fine
You can think of PTI as an extended version of SG W optimization. for its vanilla version.
In the paper, we also use e4e instead of SG W optimization in order to apply StyleCLIP.

The first step before the pivotal tuning can be whatever you want. You will receive the editing attributes of the pivot latent code you have found.

We mainly use SG W Optimization with fewer steps because it shows excellent results in the popular editing techniques

**Comment by FeiiYin** [comment]
Thanks! Got it.
